<!DOCTYPE html>
<html lang="en"><head>
<script src="2025-05-05-contamination-model-presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="2025-05-05-contamination-model-presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="2025-05-05-contamination-model-presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="2025-05-05-contamination-model-presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="2025-05-05-contamination-model-presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2025-05-05-contamination-model-presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="2025-05-05-contamination-model-presentation_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="DECDG — World Bank">
  <meta name="dcterms.date" content="2025-05-05">
  <title>Employment Misclassification with Tenure</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="2025-05-05-contamination-model-presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="2025-05-05-contamination-model-presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="2025-05-05-contamination-model-presentation_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Employment Misclassification with Tenure</h1>
  <p class="subtitle">From the Base EM Tenure Model to the Contamination Specification</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
DECDG — World Bank 
</div>
</div>
</div>

  <p class="date">2025-05-05</p>
</section>
<section id="roadmap" class="slide level2 smaller">
<h2>Roadmap</h2>
<ol type="1">
<li><strong>The Problem</strong>: Misclassified employment states in panel surveys</li>
<li><strong>Base EM Tenure Model</strong>: Latent states, tenure clocks, EM algorithm</li>
<li><strong>Why the Base Model Failed</strong>: Three empirical facts from the QLFS</li>
<li><strong>The Contamination (<span class="math inline">\varepsilon</span>) Model</strong>: Point-mass + Exponential mixture</li>
<li><strong>Preliminary Results</strong>: Parameter estimates and interpretation</li>
</ol>
<aside class="notes">
<p>30 minutes total. ~5 min setup, ~5 min base model, ~5 min diagnostics, ~10 min new model, ~5 min results.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="part-i-the-problem" class="title-slide slide level1 center">
<h1>Part I: The Problem</h1>

</section>
<section id="observed-vs.-true-employment" class="slide level2">
<h2>Observed vs.&nbsp;True Employment</h2>
<ul>
<li>Panel surveys observe employment status <span class="math inline">s_t \in \{0, 1\}</span> at quarterly waves <span class="math inline">t \in \{1,2,3\}</span></li>
<li><strong>True</strong> (latent) status is <span class="math inline">h_t \in \{0,1\}</span> — but we never see it directly</li>
<li>Employment states are <strong>misclassified</strong> with probability <span class="math inline">\pi</span>:</li>
</ul>
<p><span class="math display">
P(s_t = a \mid h_t = b) = \begin{cases}
1 - \pi &amp; \text{if } a = b \\
\pi &amp; \text{if } a \neq b
\end{cases}
</span></p>
<ul>
<li>We also observe <strong>tenure</strong> <span class="math inline">g_t \geq 0</span> (when <span class="math inline">s_t = 1</span>) and <strong>nonemployment duration</strong> category <span class="math inline">k_t</span> (when <span class="math inline">s_t = 0</span>)</li>
</ul>
</section>
<section id="the-key-question" class="slide level2">
<h2>The Key Question</h2>
<blockquote>
<p>If someone is reported as employed → nonemployed → employed, did they <strong>really</strong> change status, or is the middle wave a misclassification?</p>
</blockquote>
<p><strong>Tenure can help answer this.</strong></p>
<p>If <span class="math inline">s = (1, 0, 1)</span> and <span class="math inline">g_3 \approx g_1 + 6</span> months, the person was likely <strong>continuously employed</strong> — the middle wave was misclassified.</p>
</section></section>
<section>
<section id="part-ii-base-em-tenure-model" class="title-slide slide level1 center">
<h1>Part II: Base EM Tenure Model</h1>

</section>
<section id="latent-histories" class="slide level2">
<h2>Latent Histories</h2>
<p>The latent three-period history <span class="math inline">H = (h_1, h_2, h_3)</span> has <span class="math inline">2^3 = 8</span> possible values.</p>
<p>The <strong>Markov prior</strong> gives the probability of each history:</p>
<p><span class="math display">
p(H = h) = \alpha^{h_1}(1-\alpha)^{1-h_1} \prod_{t=2}^{3} \theta_1^{\mathbb{1}\{h_{t-1}=1, h_t=1\}} (1-\theta_1)^{\mathbb{1}\{h_{t-1}=1, h_t=0\}} \theta_0^{\mathbb{1}\{h_{t-1}=0, h_t=1\}} (1-\theta_0)^{\mathbb{1}\{h_{t-1}=0, h_t=0\}}
</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\alpha</span></td>
<td>Initial employment probability</td>
</tr>
<tr class="even">
<td><span class="math inline">\theta_1</span></td>
<td>Employment continuation probability</td>
</tr>
<tr class="odd">
<td><span class="math inline">\theta_0</span></td>
<td>Entry rate (into employment)</td>
</tr>
<tr class="even">
<td><span class="math inline">\pi</span></td>
<td>Misclassification rate</td>
</tr>
</tbody>
</table>
</section>
<section id="deterministic-tenure-clocks" class="slide level2">
<h2>Deterministic Tenure Clocks</h2>
<p>Given a latent history <span class="math inline">h</span>, tenure evolves <strong>deterministically</strong> on the quarterly grid:</p>
<ul>
<li><strong>Continuation</strong> (<span class="math inline">h_{t-1} = h_t = 1</span>): tenure increments by <span class="math inline">\Delta = 0.25</span> years (3 months)</li>
<li><strong>Start</strong> (<span class="math inline">h_{t-1} = 0, h_t = 1</span>): tenure resets</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Example</strong></p>
</div>
<div class="callout-content">
<p>If <span class="math inline">h = (1, 1, 1)</span> — three consecutive quarters of true employment:</p>
<p><span class="math display">g_1^* = T_g, \quad g_2^* = T_g + 0.25, \quad g_3^* = T_g + 0.50</span></p>
<p>where <span class="math inline">T_g \sim \text{Exp}(\lambda_g)</span> is the spell-elapsed time at wave 1.</p>
</div>
</div>
</div>
</section>
<section id="measurement-model-base" class="slide level2">
<h2>Measurement Model (Base)</h2>
<p>The base model adds <strong>Gaussian noise</strong> to tenure observations:</p>
<ul>
<li><strong>Continuation increment</strong>: <span class="math inline">\Delta^g_t = (g_t - g_{t-1}) - 0.25 \sim N(0, 2\sigma_g^2)</span></li>
<li><strong>Spell starts</strong>: <span class="math inline">g_t \sim \text{EMG}(\lambda_g, \sigma_g^2)</span> (Exponential-Modified Gaussian)</li>
<li><strong>Misclassified waves</strong>: draw from the population marginal <span class="math inline">\text{EMG}(\lambda_g, \sigma_g^2)</span></li>
</ul>
<p><strong>Parameters</strong>: <span class="math inline">\Theta = (\alpha, \theta_0, \theta_1, \pi, \sigma_g^2, \lambda_g, \lambda_d)</span> — 7 free parameters.</p>
</section>
<section id="observed-data-likelihood" class="slide level2 smaller">
<h2>Observed-Data Likelihood</h2>
<p>Each individual’s likelihood sums over all 8 latent histories — we don’t know which one generated the data:</p>
<p><span class="math display">
L_i(\Theta) = \sum_{h \in \mathcal{H}} \underbrace{p(h \mid \alpha, \theta_0, \theta_1)}_{\text{Markov prior}} \cdot \underbrace{\prod_{t=1}^{3} q_{s_{it}, h_t}(\pi)}_{\text{state misclassification}} \cdot \underbrace{\prod_{t=1}^{3} \ell_t(y_{it} \mid h; \lambda_g, \lambda_d, \sigma_g^2)}_{\text{duration emissions}}
</span></p>
<p>The <strong>log</strong> of a sum is hard to maximise directly — the <span class="math inline">\log</span> cannot be pushed inside the <span class="math inline">\sum_h</span>.</p>
<p>The observed-data log-likelihood is:</p>
<p><span class="math display">
\ell(\Theta) = \sum_{i=1}^{N} w_i \log \left[ \sum_{h \in \mathcal{H}} p(h \mid \Theta) \cdot p(y_i \mid h; \Theta) \right]
</span></p>
<p>This is a <strong>mixture log-likelihood</strong>: the <span class="math inline">\log</span> sits outside the sum over latent histories, making direct optimisation difficult.</p>
</section>
<section id="the-em-strategy" class="slide level2 smaller">
<h2>The EM Strategy</h2>
<p>The EM algorithm sidesteps the <span class="math inline">\log</span>-of-sum problem by introducing <strong>responsibilities</strong> — posterior probabilities of each latent history given the observed data.</p>
<p><strong>E-step</strong>: Compute responsibilities using Bayes’ rule:</p>
<p><span class="math display">
\gamma_{ih} = P(H_i = h \mid y_i; \Theta^{\text{old}}) = \frac{p(h \mid \Theta^{\text{old}}) \cdot p(y_i \mid h; \Theta^{\text{old}})}{\sum_{h'} p(h' \mid \Theta^{\text{old}}) \cdot p(y_i \mid h'; \Theta^{\text{old}})}
</span></p>
<p>Each <span class="math inline">\gamma_{ih}</span> is a number between 0 and 1 telling us: <em>given the current parameter estimates and this individual’s data, how likely is it that their true history is <span class="math inline">h</span>?</em></p>
<p>Note that <span class="math inline">\sum_h \gamma_{ih} = 1</span> for each individual — the responsibilities form a probability distribution over histories.</p>
</section>
<section id="from-observed-to-complete-data" class="slide level2 smaller">
<h2>From Observed to Complete Data</h2>
<p><strong>Key insight</strong>: if we <em>knew</em> the true history <span class="math inline">z_{ih} = \mathbb{1}\{H_i = h\}</span>, the log-likelihood would be:</p>
<p><span class="math display">
\log L_c(\Theta) = \sum_{i=1}^{N} \sum_{h \in \mathcal{H}} w_i z_{ih} \left[ \log p(h \mid \Theta) + \sum_t \log q_{s_{it}, h_t}(\pi) + \sum_t \log \ell_t(\cdot) \right]
</span></p>
<p>Now the <span class="math inline">\log</span> is <strong>inside</strong> — applied to each individual term, not to a sum. This is easy to maximise!</p>
<div class="fragment">
<p><strong>The EM trick</strong>: replace the unknown indicators <span class="math inline">z_{ih}</span> with their <strong>expected values</strong> under the current parameters — which are exactly the responsibilities <span class="math inline">\gamma_{ih}</span>:</p>
<p><span class="math display">
\mathbb{E}[z_{ih} \mid y_i; \Theta^{\text{old}}] = \gamma_{ih}
</span></p>
<p>So the <strong>E-step</strong> computes <span class="math inline">\gamma_{ih}</span>, and the <strong>M-step</strong> maximises <span class="math inline">\log L_c</span> with <span class="math inline">z_{ih}</span> replaced by <span class="math inline">\gamma_{ih}</span>.</p>
</div>
</section>
<section id="m-step-independent-blocks" class="slide level2 smaller">
<h2>M-Step: Independent Blocks</h2>
<p>With <span class="math inline">\gamma_{ih}</span> in hand, the complete-data log-likelihood decomposes into <strong>independent additive blocks</strong>:</p>
<p><span class="math display">
Q(\Theta \mid \Theta^{\text{old}}) = \underbrace{\sum_{i,h} w_i \gamma_{ih} \log p(h \mid \alpha, \theta_0, \theta_1)}_{\text{Block 1: Markov prior}} + \underbrace{\sum_{i,h} w_i \gamma_{ih} \sum_t \log q_{s_{it},h_t}(\pi)}_{\text{Block 2: Misclassification}} + \underbrace{\sum_{i,h} w_i \gamma_{ih} \sum_t \log \ell_t(\cdot)}_{\text{Block 3: Duration emissions}}
</span></p>
<p>Each block depends on <strong>different parameters</strong>, so they can be maximised independently:</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 44%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Block</th>
<th style="text-align: left;">Parameters</th>
<th style="text-align: left;">Update</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Markov prior</td>
<td style="text-align: left;"><span class="math inline">\alpha, \theta_0, \theta_1</span></td>
<td style="text-align: left;">Weighted frequency ratios of transitions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Misclassification</td>
<td style="text-align: left;"><span class="math inline">\pi</span></td>
<td style="text-align: left;">Weighted fraction of <span class="math inline">s_{it} \neq h_t</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duration emissions</td>
<td style="text-align: left;"><span class="math inline">\sigma_g^2, \lambda_g, \lambda_d</span></td>
<td style="text-align: left;">Weighted MLE from duration data</td>
</tr>
</tbody>
</table>
<p>Iterate E-step → M-step until <span class="math inline">\ell(\Theta)</span> converges. Monotonic convergence is guaranteed by the EM theorem.</p>
</section></section>
<section>
<section id="part-iii-why-the-base-model-failed" class="title-slide slide level1 center">
<h1>Part III: Why the Base Model Failed</h1>

</section>
<section id="three-empirical-facts" class="slide level2 smaller">
<h2>Three Empirical Facts</h2>
<p>Diagnostic analysis of the South African QLFS reveals three problems with the Gaussian measurement model:</p>
<div class="columns">
<div class="column" style="width:55%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Diagnostic</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">E→E increments exactly +3 months</td>
<td style="text-align: right;"><strong>63.2%</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">E→E increments off by &gt; 12 months</td>
<td style="text-align: right;">18.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fresh starts with tenure &gt; 12 months</td>
<td style="text-align: right;"><strong>36.7%</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">s=(1,0,1)</span> with <span class="math inline">g_3 \approx g_1 + 6</span> mo</td>
<td style="text-align: right;"><strong>27.4%</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">s=(1,0,1)</span> with <span class="math inline">g_3 \leq 3</span> mo (fresh start)</td>
<td style="text-align: right;">18.3%</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<p><strong>Key insight:</strong> The tenure increment distribution is <strong>bimodal</strong> — a huge point mass at exactly +3 months, plus a heavy-tailed residual.</p>
<p>This is a <strong>mixture</strong>, not a Gaussian.</p>
</div></div>
</section>
<section id="fact-1-tenure-is-not-gaussian" class="slide level2">
<h2>Fact 1: Tenure is Not Gaussian</h2>

<img data-src="../output/figures/tenure_diagnostics/02_ee_increment_hist.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"><p>63.2% of E→E continuation increments are <strong>exactly</strong> +3 months. The Gaussian MLE for <span class="math inline">\sigma_g^2</span> collapses to essentially zero.</p>
</section>
<section id="fact-2-tenure-corroborates-misclassification" class="slide level2">
<h2>Fact 2: Tenure Corroborates Misclassification</h2>

<img data-src="../output/figures/tenure_diagnostics/03_s101_scatter.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"><p>State pattern <span class="math inline">s = (1, 0, 1)</span>: purple dots on the dashed line (<span class="math inline">g_3 = g_1 + 6</span> mo) suggest <strong>continuous employment</strong> — the middle wave is misclassified.</p>
</section>
<section id="fact-3-impossible-fresh-starts" class="slide level2">
<h2>Fact 3: Impossible Fresh Starts</h2>

<img data-src="../output/figures/tenure_diagnostics/05_fresh_start_hist.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"><p>36.7% of within-panel fresh starts (<span class="math inline">s_{t-1}=0, s_t=1</span>) report tenure <strong>&gt; 12 months</strong>. A genuine job entry cannot have tenure exceeding <span class="math inline">\Delta = 3</span> months.</p>
</section>
<section id="the-collapse-problem" class="slide level2 smaller">
<h2>The Collapse Problem</h2>
<p>What happens when we estimate the base EM tenure model?</p>
<div class="fragment">
<ol type="1">
<li><strong><span class="math inline">\sigma_g^2</span> collapses to ~0</strong>: The 63.2% exact increments overwhelm the Gaussian MLE</li>
<li><strong><span class="math inline">\pi</span> inflates to ~26%</strong>: With <span class="math inline">\sigma_g^2 \approx 0</span>, the model has no way to explain non-exact tenure except by declaring misclassification</li>
<li><strong>Transition rates inflate</strong>: High <span class="math inline">\pi</span> drives up implied true transitions</li>
</ol>
</div>
<div class="fragment">
<p><strong>The root cause</strong>: Tenure reports that are wrong (recall error, rounding) get absorbed entirely into <span class="math inline">\pi</span>, because the model has no separate channel for tenure measurement error.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The fundamental problem</strong></p>
</div>
<div class="callout-content">
<p>The base model forces <strong>all</strong> tenure inconsistency through <span class="math inline">\pi</span> (state misclassification). It cannot distinguish between:</p>
<ul>
<li>The employment <strong>state</strong> being wrong (<span class="math inline">\pi</span>)</li>
<li>The tenure <strong>report</strong> being wrong (no parameter for this!)</li>
</ul>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-iv-the-contamination-varepsilon-model" class="title-slide slide level1 center">
<h1>Part IV: The Contamination (<span class="math inline">\varepsilon</span>) Model</h1>

</section>
<section id="the-key-idea" class="slide level2">
<h2>The Key Idea</h2>
<p>Replace the Gaussian measurement model with a <strong>point-mass + Exponential contamination mixture</strong>.</p>
<p>Each tenure observation is independently:</p>
<p><span class="math display">
g_t \mid h, m_t = \begin{cases}
g_t^*(h) &amp; \text{if } m_t = 0 \quad \text{(clean: probability } 1 - \varepsilon\text{)} \\
\text{Exp}(\lambda_g) &amp; \text{if } m_t = 1 \quad \text{(contaminated: probability } \varepsilon\text{)}
\end{cases}
</span></p>
<ul>
<li><strong>Clean</strong> (<span class="math inline">m_t = 0</span>): tenure equals the deterministic clock value <strong>exactly</strong> (point mass)</li>
<li><strong>Contaminated</strong> (<span class="math inline">m_t = 1</span>): tenure is an independent draw from <span class="math inline">\text{Exp}(\lambda_g)</span>, unrelated to the clock</li>
</ul>
<p><span class="math inline">\varepsilon</span> captures recall error, year-rounding, respondent substitution — any mechanism producing a tenure value <strong>unrelated</strong> to the true clock.</p>
</section>
<section id="two-separate-error-channels" class="slide level2">
<h2>Two Separate Error Channels</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>This is the crucial distinction</strong></p>
</div>
<div class="callout-content">

</div>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>State wrong</th>
<th>Tenure wrong</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Base model</strong></td>
<td><span class="math inline">\pi</span></td>
<td><span class="math inline">\sigma_g^2</span> (collapses)</td>
</tr>
<tr class="even">
<td><strong>Contamination model</strong></td>
<td><span class="math inline">\pi</span></td>
<td><span class="math inline">\varepsilon</span></td>
</tr>
</tbody>
</table>
<p>The contamination model has <strong>two independent error parameters</strong>:</p>
<ul>
<li><span class="math inline">\pi</span>: the employment <strong>state</strong> is misclassified</li>
<li><span class="math inline">\varepsilon</span>: the tenure <strong>report</strong> is contaminated (but the state may be correct!)</li>
</ul>
<p>This allows someone to be truly employed (<span class="math inline">h_t = 1</span>) with correct state report (<span class="math inline">s_t = 1</span>) but wrong tenure (<span class="math inline">m_t = 1</span>).</p>
</section>
<section id="spell-pair-joint-emission" class="slide level2 smaller">
<h2>Spell-Pair Joint Emission</h2>
<p>The <strong>key structural innovation</strong>: instead of evaluating each wave’s tenure independently, evaluate all observed tenure within a latent employment spell <strong>jointly</strong>.</p>
<p>A <strong>spell-pair</strong> arises when a single latent employment spell spans multiple survey waves but tenure is only observed at some of them — e.g.&nbsp;under <span class="math inline">h = (1,1,1)</span> with <span class="math inline">s = (1,0,1)</span>, waves 1 and 3 are a “pair” of tenure observations from the <strong>same</strong> underlying spell. These two flanks are structurally linked by the deterministic clock: <span class="math inline">g_3^* = g_1^* + 2\Delta</span>.</p>
<p>For a spell <span class="math inline">[a, b]</span> with observed waves <span class="math inline">\mathcal{O} = \{t_1, \ldots, t_K\}</span>:</p>
<p><span class="math display">
\ell_g^{\text{spell}} = \sum_{\mathbf{m} \in \{0,1\}^K} \left[ \prod_{t \in \mathcal{O}} \varepsilon^{m_t} (1-\varepsilon)^{1-m_t} \right] f(\{g_t\} \mid \mathbf{m}, h)
</span></p>
<p>This sums over all <span class="math inline">2^K</span> contamination patterns. The conditional density <span class="math inline">f</span> depends on which waves are clean (pinned to the clock) vs.&nbsp;contaminated (independent Exp draws).</p>
</section>
<section id="the-conditional-density-f" class="slide level2 smaller">
<h2>The Conditional Density <span class="math inline">f</span></h2>
<p>The density <span class="math inline">f(\{g_t\} \mid \mathbf{m}, h)</span> is obtained by <strong>marginalising out</strong> the latent spell-start time <span class="math inline">T_g \sim \text{Exp}(\lambda_g)</span>:</p>
<p><strong>If at least one wave is clean</strong> (<span class="math inline">\exists\, t : m_t = 0</span>), then <span class="math inline">T_g</span> is <strong>pinned</strong> by the earliest clean wave. Let <span class="math inline">t^*</span> be the first clean wave. Then <span class="math inline">T_g = g_{t^*} - (t^* - a)\Delta</span>, and:</p>
<ul>
<li>Each <strong>clean</strong> wave <span class="math inline">t \neq t^*</span>: contributes a point-mass check — does <span class="math inline">g_t = g_{t^*} + (t - t^*)\Delta</span>?</li>
<li>The <strong>pinning</strong> wave <span class="math inline">t^*</span>: contributes <span class="math inline">\lambda_g e^{-\lambda_g [g_{t^*} - (t^* - a)\Delta]}</span> (Exp density of <span class="math inline">T_g</span>)</li>
<li>Each <strong>contaminated</strong> wave: contributes <span class="math inline">\lambda_g e^{-\lambda_g g_t}</span> (independent Exp draw)</li>
</ul>
<p><strong>If all waves are contaminated</strong> (<span class="math inline">\mathcal{C} = \emptyset</span>), <span class="math inline">T_g</span> integrates out to 1 and every wave contributes an independent <span class="math inline">\text{Exp}(\lambda_g)</span> density:</p>
<p><span class="math display">
f(\{g_t\} \mid \mathbf{m} = \mathbf{1}, h) = \prod_{t \in \mathcal{O}} \lambda_g e^{-\lambda_g g_t}
</span></p>
</section>
<section id="example-the-k2-case-setup" class="slide level2 smaller">
<h2>Example: The <span class="math inline">K=2</span> Case — Setup</h2>
<p>State pattern <span class="math inline">s = (1, 0, 1)</span>, latent history <span class="math inline">h = (1, 1, 1)</span> — continuous employment, middle wave misclassified.</p>
<p>The spell runs <span class="math inline">[1, 3]</span> but tenure is observed only at waves 1 and 3 (the <strong>flanks</strong> of the spell). The spell start is <span class="math inline">a = 1</span>, so <span class="math inline">T_g = g_1^*</span> and <span class="math inline">g_3^* = T_g + 2\Delta = g_1^* + 0.5</span> yr.</p>
<p>The four contamination patterns <span class="math inline">(m_1, m_3)</span> yield <strong>structurally different densities</strong>:</p>
</section>
<section id="example-the-k2-case-four-densities" class="slide level2 smaller">
<h2>Example: The <span class="math inline">K=2</span> Case — Four Densities</h2>
<p><strong><span class="math inline">(m_1, m_3) = (0, 0)</span></strong> — Both clean. <span class="math inline">T_g</span> is pinned by <span class="math inline">g_1</span>, so <span class="math inline">g_3</span> must equal <span class="math inline">g_1 + 0.5</span>: <span class="math display">f = \lambda_g e^{-\lambda_g g_1} \cdot \mathbb{1}\{g_3 = g_1 + 2\Delta\}</span></p>
<p><strong><span class="math inline">(m_1, m_3) = (0, 1)</span></strong> — Wave 1 clean, wave 3 contaminated. <span class="math inline">T_g = g_1</span>, and <span class="math inline">g_3</span> is an independent Exp draw: <span class="math display">f = \lambda_g e^{-\lambda_g g_1} \cdot \lambda_g e^{-\lambda_g g_3} = \lambda_g^2 e^{-\lambda_g(g_1 + g_3)}</span></p>
<p><strong><span class="math inline">(m_1, m_3) = (1, 0)</span></strong> — Wave 1 contaminated, wave 3 clean. Now <span class="math inline">g_3</span> pins <span class="math inline">T_g</span>: <span class="math inline">T_g = g_3 - 2\Delta</span>, so wave 1 is an independent Exp draw and wave 3 determines the clock: <span class="math display">f = \lambda_g e^{-\lambda_g g_1} \cdot \lambda_g e^{-\lambda_g(g_3 - 2\Delta)} = \lambda_g^2 e^{-\lambda_g(g_1 + g_3 - 2\Delta)}</span></p>
<p><strong><span class="math inline">(m_1, m_3) = (1, 1)</span></strong> — Both contaminated. <span class="math inline">T_g</span> integrates out; both are independent Exp draws: <span class="math display">f = \lambda_g e^{-\lambda_g g_1} \cdot \lambda_g e^{-\lambda_g g_3} = \lambda_g^2 e^{-\lambda_g(g_1 + g_3)}</span></p>
</section>
<section id="example-the-k2-case-distinguishing-the-patterns" class="slide level2 smaller">
<h2>Example: The <span class="math inline">K=2</span> Case — Distinguishing the Patterns</h2>
<p>Notice that <span class="math inline">(0,1)</span> and <span class="math inline">(1,1)</span> produce the <strong>same</strong> functional form <span class="math inline">\lambda_g^2 e^{-\lambda_g(g_1+g_3)}</span>, but <span class="math inline">(1,0)</span> has a <strong>shift</strong> of <span class="math inline">+2\Delta</span> in the exponent:</p>
<p><span class="math display">
\ell_g^{\text{spell}} = \underbrace{(1-\varepsilon)^2 \lambda_g e^{-\lambda_g g_1} \cdot \mathbb{1}\{g_3 = g_1 + 2\Delta\}}_{\text{both clean: point mass}}
+ \underbrace{\big[(1-\varepsilon)\varepsilon + \varepsilon^2\big] \lambda_g^2 e^{-\lambda_g(g_1+g_3)}}_{(0,1) \text{ and } (1,1): \text{same form}}
+ \underbrace{\varepsilon(1-\varepsilon) \lambda_g^2 e^{-\lambda_g(g_1+g_3-2\Delta)}}_{(1,0): \text{shifted by } e^{+\lambda_g \cdot 2\Delta}}
</span></p>
<p><strong>When <span class="math inline">g_3 = g_1 + 0.5</span> yr</strong>: the all-clean pattern fires its point mass → strong evidence for continuous employment → pushes <span class="math inline">\gamma</span> toward <span class="math inline">h = (1,1,1)</span> → increases implied <span class="math inline">\pi</span>.</p>
<p><strong>When <span class="math inline">g_3 \neq g_1 + 0.5</span> yr</strong>: the point-mass term is zero, but the three continuous terms remain active. The <span class="math inline">(1,0)</span> term is distinguished from the others by the shift factor <span class="math inline">e^{\lambda_g \cdot 2\Delta}</span>.</p>
</section>
<section id="identifying-varepsilon" class="slide level2 smaller">
<h2>Identifying <span class="math inline">\varepsilon</span></h2>
<p><span class="math inline">\varepsilon</span> is identified from the empirical fraction of tenure observations that are <strong>exactly clock-consistent</strong>.</p>
<p><strong>Source 1 — Adjacent E→E pairs</strong> (<span class="math inline">s_{t-1} = s_t = 1</span>, <span class="math inline">h_{t-1} = h_t = 1</span>):</p>
<ul>
<li>These are consecutive employed waves where both tenure values are observed.</li>
<li>If <span class="math inline">m_t = 0</span> (clean), the increment <span class="math inline">g_t - g_{t-1}</span> must equal exactly <span class="math inline">\Delta = 0.25</span> yr.</li>
<li>The indicator <span class="math inline">\mathbb{1}\{g_t - g_{t-1} = \Delta\}</span> is Bernoulli with mean <span class="math inline">1 - \varepsilon</span>.</li>
<li>Empirically, <strong>63.2%</strong> satisfy this → <span class="math inline">\hat{\varepsilon}_{\text{MoM}} = 1 - 0.632 \approx 0.37</span>.</li>
</ul>
<p><strong>Source 2 — Two-wave bridges</strong> (<span class="math inline">s = (1, 0, 1)</span> under <span class="math inline">h = (1, 1, 1)</span>):</p>
<ul>
<li>These are panels where the individual is observed as employed at waves 1 and 3 but nonemployed at wave 2, yet is <strong>truly employed throughout</strong> — the wave-2 nonemployment is a misclassification.</li>
<li>Tenure is observed only at the two “flanks” (waves 1 and 3). If <strong>both</strong> are clean, <span class="math inline">g_3 = g_1 + 2\Delta</span>.</li>
<li>The indicator <span class="math inline">\mathbb{1}\{g_3 = g_1 + 2\Delta\}</span> is Bernoulli with mean <span class="math inline">(1-\varepsilon)^2</span> (both waves must be independently clean).</li>
<li>Empirically, <strong>27.4%</strong> satisfy this → <span class="math inline">\hat{\varepsilon}_{\text{MoM}} = 1 - \sqrt{0.274} \approx 0.48</span>.</li>
</ul>
<p>The EM estimate combines both sources via responsibility-weighted averaging, yielding <span class="math inline">\hat{\varepsilon} \approx 25\%</span> (lower than MoM because the EM correctly accounts for genuine transitions).</p>
</section>
<section id="identifying-pi-the-corroboration-channel" class="slide level2 smaller">
<h2>Identifying <span class="math inline">\pi</span> — The Corroboration Channel</h2>
<p>In the base model (and the simple model without tenure), <span class="math inline">\pi</span> is identified <strong>only</strong> from the frequencies of the 8 observed state patterns <span class="math inline">s = (s_1, s_2, s_3)</span> — i.e.&nbsp;from <strong>state-Markov violations</strong> alone.</p>
<p>The contamination model adds a <strong>second identification channel</strong>: <strong>tenure-flank consistency</strong> within spell-pairs.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>What is a spell-pair?</strong></p>
</div>
<div class="callout-content">
<p>A “spell-pair” is a pair of tenure observations that belong to the <strong>same latent employment spell</strong> but are separated by one or more waves where the individual reports nonemployment. For example, under <span class="math inline">s = (1,0,1)</span> with <span class="math inline">h = (1,1,1)</span>, waves 1 and 3 are a spell-pair — two tenure “flanks” of the same continuous job spell.</p>
</div>
</div>
</div>
<p><strong>How tenure flanks identify <span class="math inline">\pi</span></strong>:</p>
<ul>
<li>When <span class="math inline">s = (1,0,1)</span> and <span class="math inline">g_3 \approx g_1 + 0.5</span> yr (27.4% of cases): the spell-pair point mass fires → the posterior <span class="math inline">\gamma</span> is pushed strongly toward <span class="math inline">h = (1,1,1)</span> → this counts wave 2 as a misclassification, contributing to <span class="math inline">\hat{\pi}</span>.</li>
<li>When <span class="math inline">s = (1,0,1)</span> and <span class="math inline">g_3 \leq 3</span> months (18.3% of cases): tenure looks like a fresh start → consistent with <span class="math inline">h = (1,0,1)</span> (genuine transition) → does <strong>not</strong> contribute to misclassification.</li>
<li>When <span class="math inline">s = (0,1,0)</span> with matching timegap categories <span class="math inline">k_1 = k_3</span> (63.7% of cases): similar logic — timegap consistency pushes <span class="math inline">\gamma</span> toward <span class="math inline">h = (0,0,0)</span>.</li>
</ul>
<p>The result: <span class="math inline">\hat{\pi}</span> is identified from <strong>both</strong> state-Markov violations <strong>and</strong> tenure-flank consistency. Tenure data <strong>corroborates and refines</strong> the misclassification estimate.</p>
</section>
<section id="how-varepsilon-affects-the-posterior" class="slide level2 smaller">
<h2>How <span class="math inline">\varepsilon</span> Affects the Posterior</h2>
<p><span class="math inline">\varepsilon</span> enters <span class="math inline">\gamma_{ih}</span> <strong>only</strong> through the spell-pair emission <span class="math inline">\ell_g^{\text{spell}}</span> — it does not appear in the Markov prior or in singleton-spell emissions.</p>
<p>Consider <span class="math inline">s = (1,0,1)</span> with two competing histories:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><span class="math inline">h = (1,1,1)</span> (spell-pair)</th>
<th style="text-align: left;"><span class="math inline">h = (1,0,1)</span> (two singletons)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Emission</td>
<td style="text-align: left;"><span class="math inline">\ell_g^{\text{spell}}</span> from Eq. — <strong>depends on <span class="math inline">\varepsilon</span></strong></td>
<td style="text-align: left;"><span class="math inline">\lambda_g e^{-\lambda_g g_1} \cdot \lambda_g e^{-\lambda_g g_3}</span> — <strong>no <span class="math inline">\varepsilon</span></strong></td>
</tr>
</tbody>
</table>
<p><strong><span class="math inline">\varepsilon</span> controls the discrimination power of tenure evidence:</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Low <span class="math inline">\varepsilon</span></strong> (most reports are clean):</p>
<ul>
<li>Clock-consistent flanks → point mass fires → <span class="math inline">\gamma_{(1,1,1)}</span> very high</li>
<li>Clock-inconsistent flanks → point mass = 0, contamination terms are small → <span class="math inline">\gamma_{(1,1,1)}</span> very low</li>
<li>Tenure <strong>strongly</strong> informs <span class="math inline">\pi</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>High <span class="math inline">\varepsilon</span></strong> (many reports are contaminated):</p>
<ul>
<li>Clock-consistent → point mass still dominates but weighted by smaller <span class="math inline">(1-\varepsilon)^2</span></li>
<li>Clock-inconsistent → contamination terms are larger → <span class="math inline">\gamma_{(1,1,1)}</span> <strong>increases</strong> (tenure inconsistency is “explained away” as contamination)</li>
<li>Tenure <strong>weakly</strong> informs <span class="math inline">\pi</span>; Markov prior dominates</li>
</ul>
</div></div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\varepsilon</span> governs how <strong>informative</strong> tenure is; <span class="math inline">\pi</span> governs how much misclassification there <strong>actually is</strong>. The EM finds the <span class="math inline">(\varepsilon, \pi)</span> pair that jointly explains both the clock-consistency rate and the state-pattern frequencies.</p>
</div>
</div>
</div>
</div>
</section>
<section id="worked-example-base-model" class="slide level2 smaller">
<h2>Worked Example: Base Model</h2>
<p>Consider an individual with <span class="math inline">s = (1,1,1)</span> and tenure <span class="math inline">g = (1.0,\; 5.0,\; 1.5)</span> years.</p>
<p>Under <span class="math inline">h = (1,1,1)</span> (continuous employment), the clock predicts: <span class="math display">g_1^* = T_g, \quad g_2^* = T_g + 0.25, \quad g_3^* = T_g + 0.50</span></p>
<p>The <strong>observed increments</strong> are:</p>
<ul>
<li><span class="math inline">g_2 - g_1 = 4.0</span> years (should be <span class="math inline">+0.25</span>) — off by <strong>3.75 years</strong></li>
<li><span class="math inline">g_3 - g_2 = -3.5</span> years (should be <span class="math inline">+0.25</span>) — off by <strong>3.75 years</strong></li>
</ul>
<p>With <span class="math inline">\sigma_g^2 \approx 0</span>, the Gaussian increment density assigns <strong>near-zero</strong> likelihood to these deviations under <span class="math inline">h = (1,1,1)</span>.</p>
<p>The model is <strong>forced</strong> to declare <span class="math inline">h = (1,0,1)</span>: the individual truly left employment at wave 2 and re-entered at wave 3. This requires:</p>
<ul>
<li>A true transition <span class="math inline">1 \to 0</span> between waves 1–2</li>
<li>A true transition <span class="math inline">0 \to 1</span> between waves 2–3</li>
<li>A misclassification at wave 2 (<span class="math inline">s_2 = 1</span> but <span class="math inline">h_2 = 0</span>)</li>
</ul>
<p>→ Both <span class="math inline">\pi</span> and transition rates are <strong>inflated</strong> to accommodate tenure inconsistency.</p>
</section>
<section id="worked-example-contamination-model" class="slide level2 smaller">
<h2>Worked Example: Contamination Model</h2>
<p>Same individual: <span class="math inline">s = (1,1,1)</span>, tenure <span class="math inline">g = (1.0,\; 5.0,\; 1.5)</span> years.</p>
<p>Under <span class="math inline">h = (1,1,1)</span>, the spell emission sums over <span class="math inline">2^3 = 8</span> contamination patterns. Consider the pattern <span class="math inline">\mathbf{m} = (0, 1, 0)</span> — waves 1 and 3 clean, wave 2 contaminated:</p>
<ul>
<li><strong>Wave 1</strong> (<span class="math inline">m_1 = 0</span>, clean): <span class="math inline">T_g = g_1 = 1.0</span> yr. Density: <span class="math inline">\lambda_g e^{-\lambda_g \cdot 1.0}</span> ✓</li>
<li><strong>Wave 2</strong> (<span class="math inline">m_2 = 1</span>, contaminated): <span class="math inline">g_2 = 5.0</span> is just an independent Exp draw. Density: <span class="math inline">\lambda_g e^{-\lambda_g \cdot 5.0}</span> ✓</li>
<li><strong>Wave 3</strong> (<span class="math inline">m_3 = 0</span>, clean): must satisfy <span class="math inline">g_3 = g_1 + 2\Delta = 1.5</span> yr. ✓ <strong>It does!</strong></li>
</ul>
<p>So the clock-consistency check <strong>passes</strong> for waves 1 and 3 (they are 0.5 yr apart, exactly <span class="math inline">2\Delta</span>), and wave 2’s outlier tenure is absorbed by the contamination branch.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The key difference</strong></p>
</div>
<div class="callout-content">
<p><strong>No state misclassification is needed.</strong> The individual is truly employed throughout (<span class="math inline">h = (1,1,1)</span>), correctly reported as employed (<span class="math inline">s = (1,1,1)</span>), but wave 2’s tenure is simply a bad report (<span class="math inline">m_2 = 1</span>). This keeps <span class="math inline">\pi</span> and transition rates at sensible levels.</p>
</div>
</div>
</div>
</section>
<section id="parameters-base-vs.-contamination" class="slide level2">
<h2>Parameters: Base vs.&nbsp;Contamination</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Base EM Tenure</th>
<th style="text-align: left;">Contamination</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Markov</td>
<td style="text-align: left;"><span class="math inline">\alpha, \theta_0, \theta_1</span></td>
<td style="text-align: left;"><span class="math inline">\alpha, \theta_0, \theta_1</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Misclassification</td>
<td style="text-align: left;"><span class="math inline">\pi</span></td>
<td style="text-align: left;"><span class="math inline">\pi</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tenure measurement</td>
<td style="text-align: left;"><span class="math inline">\sigma_g^2</span> (collapses)</td>
<td style="text-align: left;"><span class="math inline">\varepsilon</span> (contamination rate)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spell distribution</td>
<td style="text-align: left;">EMG<span class="math inline">(\lambda_g, \sigma_g^2)</span></td>
<td style="text-align: left;">Exp<span class="math inline">(\lambda_g)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">N-spell rate</td>
<td style="text-align: left;"><span class="math inline">\lambda_d</span></td>
<td style="text-align: left;"><span class="math inline">\lambda_d</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total free parameters</strong></td>
<td style="text-align: left;"><strong>7</strong></td>
<td style="text-align: left;"><strong>7</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tenure → <span class="math inline">\pi</span> ID</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;"><strong>Yes</strong> (spell-pair)</td>
</tr>
</tbody>
</table>
<p>Same parameter count, but fundamentally different structure.</p>
</section></section>
<section>
<section id="part-v-preliminary-results" class="title-slide slide level1 center">
<h1>Part V: Preliminary Results</h1>

</section>
<section id="estimation-results" class="slide level2 smaller">
<h2>Estimation Results</h2>
<div style="font-size: 0.85em;">
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 40%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">No ME</th>
<th style="text-align: right;">Simple ME</th>
<th style="text-align: right;">Contamination (Linked)</th>
<th style="text-align: right;"><strong>Contamination (Stat-Linked)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Entry rate <span class="math inline">\theta_0</span> (%)</td>
<td style="text-align: right;">8.34</td>
<td style="text-align: right;">2.90</td>
<td style="text-align: right;">4.08</td>
<td style="text-align: right;"><strong>4.14</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Exit rate <span class="math inline">1 - \theta_1</span> (%)</td>
<td style="text-align: right;">8.36</td>
<td style="text-align: right;">2.91</td>
<td style="text-align: right;">4.26</td>
<td style="text-align: right;"><strong>4.26</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Misclassification <span class="math inline">\pi</span> (%)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">2.98</td>
<td style="text-align: right;">10.21</td>
<td style="text-align: right;"><strong>10.02</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Contamination <span class="math inline">\varepsilon</span> (%)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">24.79</td>
<td style="text-align: right;"><strong>24.69</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\lambda_g</span></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.174</td>
<td style="text-align: right;"><strong>0.174</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\lambda_d</span></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.167</td>
<td style="text-align: right;"><strong>0.169</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean E-spell (months)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">68.9</td>
<td style="text-align: right;"><strong>68.9</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean N-spell (months)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">72.0</td>
<td style="text-align: right;"><strong>71.0</strong></td>
</tr>
</tbody>
</table>
</div>

<aside><div>
<p>Simple models: MLE on 3-wave state sequences (<span class="math inline">N = 22{,}779</span>). Contamination: EM on 3-wave panels with tenure/timegap (<span class="math inline">N = 402{,}923</span>). “Linked” = CTMC constraint. “Stat” = stationarity.</p>
</div></aside></section>
<section id="key-findings" class="slide level2 smaller">
<h2>Key Findings</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="contamination-rate">Contamination rate</h3>
<ul>
<li><span class="math inline">\hat{\varepsilon} \approx 25\%</span> — stable across specifications</li>
<li><strong>Below</strong> method-of-moments (37–48%), because the EM accounts for genuine transitions explaining some non-exact increments</li>
</ul>
<h3 id="misclassification-rate">Misclassification rate</h3>
<ul>
<li><span class="math inline">\hat{\pi} \approx 10\%</span> — <strong>substantially above</strong> the simple model’s 3%</li>
<li>The corroboration channel: tenure flanks provide direct evidence that observed <span class="math inline">(1 \to 0 \to 1)</span> sequences are often misclassified continuous employment</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="transition-rates">Transition rates</h3>
<ul>
<li>Entry: <span class="math inline">\hat{\theta}_0 = 4.1\%</span>; Exit: <span class="math inline">1 - \hat{\theta}_1 = 4.3\%</span></li>
<li><strong>Between</strong> naïve (8.3%) and simple ME (2.9%)</li>
<li>Naïve overstates transitions (counts misclassifications as transitions)</li>
<li>Simple ME understates them (lacks tenure information to properly identify <span class="math inline">\pi</span>)</li>
</ul>
<h3 id="model-fit">Model fit</h3>
<ul>
<li>Consistent with descriptive evidence
<ul>
<li>36.7% impossible fresh starts → <span class="math inline">\pi</span> should be well above 3%</li>
<li>63.2% exact increments → <span class="math inline">\varepsilon</span> should be below 37%</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>What the contamination model achieves</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Eliminates <span class="math inline">\sigma_g^2</span> collapse</strong> — no Gaussian noise parameter to degenerate</li>
<li><strong>Separates state vs.&nbsp;tenure error</strong> — <span class="math inline">\pi</span> for states, <span class="math inline">\varepsilon</span> for tenure</li>
<li><strong>Tenure corroborates <span class="math inline">\pi</span></strong> — spell-pair flanks provide a new identification channel</li>
<li><strong>Plausible estimates</strong> — <span class="math inline">\pi \approx 10\%</span>, consistent with descriptive evidence</li>
</ol>
</div>
</div>
</div>
<h3 id="next-steps">Next steps</h3>
<ul>
<li>Robustness: compare linked vs.&nbsp;free specifications more closely</li>
<li>Simulation study: verify parameter recovery under known DGP</li>
<li>Extension: incorporate covariates</li>
<li>Full write-up for publication</li>
</ul>
</section>
<section id="appendix-file-structure" class="slide level2 smaller">
<h2>Appendix: File Structure</h2>
<p>Key files in <code>EM-tenure/</code>:</p>
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">File</th>
<th style="text-align: left;">Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>R/em_driver_eps.R</code></td>
<td style="text-align: left;">Main EM driver for the <span class="math inline">\varepsilon</span> model</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>R/emissions_eps.R</code></td>
<td style="text-align: left;">Spell-pair joint emission densities</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>R/estep_eps.R</code></td>
<td style="text-align: left;">E-step: responsibilities + contamination posteriors</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>R/mstep_eps.R</code></td>
<td style="text-align: left;">M-step: parameter updates</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>R/init_params_eps.R</code></td>
<td style="text-align: left;">Starting values (cold start or warm from base)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>R/simulate.R</code></td>
<td style="text-align: left;">Panel data simulator (supports <span class="math inline">\varepsilon</span> model)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>estimate_pipeline.R</code></td>
<td style="text-align: left;">Runs all model variants, saves results</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>tests/test-eps-model.R</code></td>
<td style="text-align: left;">Unit tests for the <span class="math inline">\varepsilon</span> model</td>
</tr>
</tbody>
</table>


<aside><div>
<p>Documentation: <code>documents/EM tenure.tex</code> (base model), <code>documents/EM tenure epsilon.tex</code> (contamination model)</p>
</div></aside></section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="2025-05-05-contamination-model-presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>